export { usePredictions } from './usePredictions'
export { useFeed } from './useFeed'
export { useConnections, type Connection } from './useConnections'
export { useCampfire } from './useCampfire'
export { useIntegrityMaps, type IntegrityMap } from './useIntegrityMaps'
export { useIsCoach } from './useIsCoach'
export { useCoachClients, type CoachClient } from './useCoachClients'
export { useClientDetail, type ClientDetail, type ActivityItem } from './useClientDetail'
export { useCoachingSessions, type CoachingSession, type ScheduledSession, type SessionTranscript } from './useCoachingSessions'
export { useCoachingNotes, type CoachingNote } from './useCoachingNotes'
export { useZoneData, type ZoneData } from './useZoneData'
export { useMapData, type MapData } from './useMapData'
export { useStoryData, type StoryData } from './useStoryData'

// P0 Hooks - Together/Campfire rebuild (Jan 2026)
export { useActivityCounts, type ActivityCounts } from './useActivityCounts'
export { useThisWeeksEvidence, type EvidenceItem } from './useThisWeeksEvidence'
export { useNoticingInOthers, type NoticingData } from './useNoticingInOthers'
export { useTrajectory, type TrajectoryPoint } from './useTrajectory'
export { useYoursVsOthers, type FiresComparison } from './useYoursVsOthers'
export { useExchangeImpacts, type ExchangeImpact } from './useExchangeImpacts'
export { usePendingAsks, type PendingAsk } from './usePendingAsks'

// P1 Hooks - Exchange actions
export { useExchangeActions, type ImpactLevel } from './useExchangeActions'
